// src/data/CarData.js

const carData = [
  {
    id: "1",
    name: "تويوتا كورولا 2020",
    model: "كورولا",
    make: "تويوتا",
    year: 2020,
    fuel: "بنزين",
    transmission: "أوتوماتيك",
    color: "أبيض",
    price: "13000",
    city: "دمشق",
    status: "جديدة",
    image: "/images/car1.jpg",
  },
  {
    id: "2",
    name: "كيا سيراتو 2019",
    model: "سيراتو",
    make: "كيا",
    year: 2019,
    fuel: "بنزين",
    transmission: "عادي",
    color: "أسود",
    price: "11000",
    city: "حلب",
    status: "مستعملة",
    image: "/images/car2.jpg",
  },
  {
    id: "3",
    name: "هيونداي توسان 2021",
    model: "توسان",
    make: "هيونداي",
    year: 2021,
    fuel: "ديزل",
    transmission: "أوتوماتيك",
    color: "رمادي",
    price: "18000",
    city: "اللاذقية",
    status: "جديدة",
    image: "/images/car3.jpg",
  },
  {
    id: "4",
    name: "فورد فوكس 2018",
    model: "فوكس",
    make: "فورد",
    year: 2018,
    fuel: "بنزين",
    transmission: "عادي",
    color: "أزرق",
    price: "9500",
    city: "حمص",
    status: "مستعملة",
    image: "/images/car4.jpg",
  },
  {
    id: "5",
    name: "نيسان سنترا 2022",
    model: "سنترا",
    make: "نيسان",
    year: 2022,
    fuel: "بنزين",
    transmission: "أوتوماتيك",
    color: "أحمر",
    price: "14000",
    city: "طرطوس",
    status: "جديدة",
    image: "/images/car5.jpg",
  },
  // أضف المزيد من السيارات حسب الحاجة
];

export default carData;